fail_fast: false
default_stages: [pre-commit]

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-json
      - id: check-merge-conflict
      - id: check-yaml
      - id: end-of-file-fixer
      - id: pretty-format-json
        args:
          - --autofix
      - id: trailing-whitespace
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.100.0
    hooks:
      - id: terraform_fmt
        args:
          - --args=-write=true
      - id: terraform_tflint
        args:
          - --args=--config=__GIT_WORKING_DIR__/infra/.tflint.hcl
      - id: terraform_trivy
        args:
          - --args=--config=__GIT_WORKING_DIR__/infra/trivy.yml
