name: Deploy Infrastructure

on:
    pull_request:
        types: [closed]
        branches: [main]
        paths: ["infra/infra-website/**"]
    workflow_dispatch:

permissions:
    actions: read
    contents: read
    id-token: write

jobs:
    deploy-infra:
        name: "OpenTofu"
        runs-on: ubuntu-latest
        environment: infra-prod
        if: github.event.pull_request.merged == true
        defaults:
            run:
                shell: bash
                working-directory: ${{ env.tf_actions_working_dir }}
        env:
            tf_actions_working_dir: "infra/infra-website"

        steps:
            - name: Checkout repo
              uses: actions/checkout@v5

            - name: Configure AWS credentials
              uses: aws-actions/configure-aws-credentials@v5
              with:
                  role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
                  aws-region: ${{ secrets.AWS_REGION }}

            - name: Download OpenTofu Plan Artifact
              uses: dawidd6/action-download-artifact@v11
              with:
                  if_no_artifact_found: fail
                  name: opentofu-plan
                  path: infra/infra-website
                  pr: ${{ github.event.pull_request.number }}
                  use_unzip: true
                  workflow: infra-plan.yml

            - name: Setup OpenTofu
              uses: opentofu/setup-opentofu@v1

            - name: OpenTofu Init
              id: init
              run: tofu init -backend-config="bucket=${{ secrets.TF_STATE_BUCKET }}"

            - name: Terraform Apply
              run: tofu apply -auto-approve -input=false tfplan
